#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : kcolorpicker
Version  : 0.2.0
Release  : 1
URL      : https://github.com/ksnip/kColorPicker/archive/refs/tags/v0.2.0.tar.gz
Source0  : https://github.com/ksnip/kColorPicker/archive/refs/tags/v0.2.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : LGPL-3.0
Requires: kcolorpicker-lib = %{version}-%{release}
Requires: kcolorpicker-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : qtbase-dev mesa-dev

%description
# kColorPicker [![Build Status][github-badge]][github-url]
QToolButton with color popup menu with lets you select a color. The popup features a color dialog button which can be used to add custom colors to the popup menu.

%package dev
Summary: dev components for the kcolorpicker package.
Group: Development
Requires: kcolorpicker-lib = %{version}-%{release}
Provides: kcolorpicker-devel = %{version}-%{release}
Requires: kcolorpicker = %{version}-%{release}

%description dev
dev components for the kcolorpicker package.


%package lib
Summary: lib components for the kcolorpicker package.
Group: Libraries
Requires: kcolorpicker-license = %{version}-%{release}

%description lib
lib components for the kcolorpicker package.


%package license
Summary: license components for the kcolorpicker package.
Group: Default

%description license
license components for the kcolorpicker package.


%prep
%setup -q -n kColorPicker-0.2.0
cd %{_builddir}/kColorPicker-0.2.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1661784312
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
%cmake ..
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1661784312
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/kcolorpicker
cp %{_builddir}/kColorPicker-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/kcolorpicker/a8a12e6867d7ee39c21d9b11a984066099b6fb6b || :
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/kColorPicker/KColorPicker.h
/usr/include/kColorPicker/KColorPickerExport.h
/usr/lib64/cmake/kColorPicker/kColorPicker-targets-relwithdebinfo.cmake
/usr/lib64/cmake/kColorPicker/kColorPicker-targets.cmake
/usr/lib64/cmake/kColorPicker/kColorPickerConfig-version.cmake
/usr/lib64/cmake/kColorPicker/kColorPickerConfig.cmake
/usr/lib64/libkColorPicker.so

%files lib
%defattr(-,root,root,-)
/usr/lib64/libkColorPicker.so.0
/usr/lib64/libkColorPicker.so.0.2.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/kcolorpicker/a8a12e6867d7ee39c21d9b11a984066099b6fb6b
